### ISSUE TITLE
V2 Themes Preview Pictures Are Broken

### ISSUE THREAD

**Issue by ItzKoolKid96** [Votion-Development/Dashactyl-Themes#8]
[DashactylV2-Corona-Theme](https://github.com/Votion-Development/Dashactyl-Themes/tree/main/DashactylV2-Corona-Theme)
[DashactylV2-Argon-Theme](https://github.com/Votion-Development/Dashactyl-Themes/tree/main/DashactylV2-Argon-Theme)

**Comment by devnote-dev** [comment]
Contact the author, nothing we can do about it.

**Comment by acktarcodes** [comment]
fixed :d
